// test/svg.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import { inlineSvg } from "../scripts/svg.mjs";

const SAMPLE = `<!-- Generated by graphviz version 15.1.1 -->
<!-- Pages: 1 -->
<svg width="1961pt" height="511pt"
 viewBox="0.00 0.00 1961.00 511.00" xmlns="http://www.w3.org/2000/svg">
<g id="graph0" class="graph"><title>G</title>
<polygon fill="white" points="0,0 0,0"/>
<g id="node1" class="node"><ellipse clip-path="url(#clip0)" fill="none"/></g>
<clipPath id="clip0"><rect/></clipPath>
<use xlink:href="#node1"/>
</g></svg>`;

test("graphviz 주석 헤더를 잘라낸다", () => {
  const { svg } = inlineSvg(SAMPLE, "d1before");
  assert.ok(svg.startsWith("<svg"), `실제 시작: ${svg.slice(0, 40)}`);
});

test("width/height 속성을 제거하고 viewBox 는 남긴다", () => {
  const { svg } = inlineSvg(SAMPLE, "d1before");
  const openTag = svg.slice(0, svg.indexOf(">") + 1);
  assert.ok(!/\bwidth=/.test(openTag), "width 가 남아 있다");
  assert.ok(!/\bheight=/.test(openTag), "height 가 남아 있다");
  assert.ok(openTag.includes('viewBox="0.00 0.00 1961.00 511.00"'), "viewBox 가 사라졌다");
});

test("pt 를 px 로 환산해 원본 크기를 돌려준다", () => {
  const { naturalWidthPx, naturalHeightPx } = inlineSvg(SAMPLE, "d1before");
  assert.equal(naturalWidthPx, 2615);   // 1961 * 4/3 = 2614.67
  assert.equal(naturalHeightPx, 681);   // 511 * 4/3 = 681.33
});

test("모든 id 에 접두사를 붙인다", () => {
  const { svg } = inlineSvg(SAMPLE, "d1before");
  assert.ok(svg.includes('id="d1before-graph0"'));
  assert.ok(svg.includes('id="d1before-node1"'));
  assert.ok(svg.includes('id="d1before-clip0"'));
});

test("url(#...) 참조도 함께 치환한다", () => {
  const { svg } = inlineSvg(SAMPLE, "d1before");
  assert.ok(svg.includes("url(#d1before-clip0)"), "clip-path 참조가 안 바뀌면 렌더가 깨진다");
});

test("xlink:href 참조도 함께 치환한다", () => {
  const { svg } = inlineSvg(SAMPLE, "d1before");
  assert.ok(svg.includes('xlink:href="#d1before-node1"'));
});

test("접두사가 다르면 두 SVG 의 id 가 충돌하지 않는다", () => {
  const a = inlineSvg(SAMPLE, "d1before").svg;
  const b = inlineSvg(SAMPLE, "d1after").svg;
  assert.ok(a.includes('id="d1before-graph0"'));
  assert.ok(b.includes('id="d1after-graph0"'));
  assert.ok(!b.includes('id="d1before-graph0"'));
});

test("<svg> 가 없으면 던진다", () => {
  assert.throws(() => inlineSvg("<html></html>", "x"), /svg/i);
});
