import pytest
from viz.svg import inlineSvg

SAMPLE = """<!-- Generated by graphviz version 15.1.1 -->
<!-- Pages: 1 -->
<svg width="1961pt" height="511pt"
 viewBox="0.00 0.00 1961.00 511.00" xmlns="http://www.w3.org/2000/svg">
<g id="graph0" class="graph"><title>G</title>
<polygon fill="white" points="0,0 0,0"/>
<g id="node1" class="node"><ellipse clip-path="url(#clip0)" fill="none"/></g>
<clipPath id="clip0"><rect/></clipPath>
<use xlink:href="#node1"/>
</g></svg>"""

def test_graphviz_comments_removed():
    res = inlineSvg(SAMPLE, "d1before")
    assert res["svg"].startswith("<svg")

def test_width_height_removed_viewbox_kept():
    res = inlineSvg(SAMPLE, "d1before")
    svg = res["svg"]
    openTag = svg[:svg.find(">")+1]
    assert "width=" not in openTag
    assert "height=" not in openTag
    assert 'viewBox="0.00 0.00 1961.00 511.00"' in openTag

def test_pt_to_px_conversion():
    res = inlineSvg(SAMPLE, "d1before")
    assert res["naturalWidthPx"] == 2615
    assert res["naturalHeightPx"] == 681

def test_ids_prefixed():
    res = inlineSvg(SAMPLE, "d1before")
    svg = res["svg"]
    assert 'id="d1before-graph0"' in svg
    assert 'id="d1before-node1"' in svg
    assert 'id="d1before-clip0"' in svg

def test_url_references_prefixed():
    res = inlineSvg(SAMPLE, "d1before")
    assert "url(#d1before-clip0)" in res["svg"]

def test_xlink_href_prefixed():
    res = inlineSvg(SAMPLE, "d1before")
    assert 'xlink:href="#d1before-node1"' in res["svg"]

def test_prefix_prevents_id_collision():
    a = inlineSvg(SAMPLE, "d1before")["svg"]
    b = inlineSvg(SAMPLE, "d1after")["svg"]
    assert 'id="d1before-graph0"' in a
    assert 'id="d1after-graph0"' in b
    assert 'id="d1before-graph0"' not in b

def test_throws_if_no_svg_tag():
    with pytest.raises(ValueError, match="svg"):
        inlineSvg("<html></html>", "x")
