import type { ReportData, Term } from "report-builder/types";

// 용어집 — 정의는 여기 한 곳에만 있다. 본문 인라인 참조도, 관계 그래프도 이 배열에서 나온다.
// 읽는 사람은 배경 지식이 없다고 가정하고 쓴다.
export const terms: Term[] = [
  { id: "C-19", kind: "decision",
    label: "C-19 호출 관계 수집",
    short: "코드를 읽지 않고도 \u0027A 가 B 를 부른다\u0027 를 알 수 있게, 호출 관계 목록을 미리 뽑아 두기로 한 결정",
    body: "지금은 위키를 쓰는 인공지능이 그 사실을 알려고 소스 코드 본문을 직접 읽는다. 미리 뽑아 두면 읽을 이유가 사라진다. 다만 이 목록을 코드 지도의 간선으로 승격하지는 않는다.",
    links: ["calls[]", "roslyn-dump.json", "codegraph.json"] },
  { id: "C-20", kind: "decision",
    label: "C-20 요약 캐시",
    short: "파일마다 한 번 읽고 만든 요약을 저장해 두고, 파일이 바뀌었는지는 git 이 이미 가진 지문으로 판별하기로 한 결정",
    body: "같은 파일을 매번 다시 읽지 않게 한다. 판정은 유효 / 낡음 / 판정불가 세 값이다.",
    links: ["WarmUp", "git blob SHA", "무효화"] },
  { id: "C-21", kind: "decision",
    label: "C-21 두 계층 가르기",
    short: "모든 모듈을 똑같이 정독하지 않고, 중요한 소수만 정독하고 나머지는 개요만 보기로 한 결정",
    body: "무엇이 중요한지는 이미 계산해 둔 세 기준으로 정한다. 무엇을 생략할지는 도구가 정하지 않는다.",
    links: ["PageRank", "hotspot", "모듈"] },
  { id: "calls[]", kind: "artifact",
    label: "calls[]",
    short: "누가 누구를 부르는지를 모아 둔 목록. 대괄호는 여러 개가 담긴 배열이라는 표시다",
    links: ["roslyn-dump.json"] },
  { id: "roslyn-dump.json", kind: "artifact",
    label: "roslyn-dump.json",
    short: "C# 코드를 Roslyn 이라는 분석기로 훑어서 나온 원자료 파일. 클래스 이름, 관계, 위치가 들어 있다",
    links: ["codegraph.json"] },
  { id: "codegraph.json", kind: "artifact",
    label: "codegraph.json",
    short: "원자료를 정리해 만든 코드 지도. 점(클래스)과 선(관계)으로 이루어진다",
    links: ["edges[]"] },
  { id: "edges[]", kind: "artifact",
    label: "edges[]",
    short: "코드 지도의 선 목록. 무엇이 무엇에 기대고 있는지를 담는다",
    body: "C-19 이 뽑는 호출 관계는 이 목록에 넣지 않는다. 성격이 다른 축이기 때문이다." },
  { id: "WarmUp", kind: "concept",
    label: "WarmUp",
    short: "미리 데워 둔다는 뜻. 여기서는 파일별 요약을 미리 만들어 두고 다음 번에 다시 쓰는 것을 말한다" },
  { id: "무효화", kind: "concept",
    label: "무효화",
    short: "저장해 둔 값이 더 이상 맞지 않게 됐다고 표시하는 것. 원본이 바뀌면 캐시를 버려야 한다" },
  { id: "git blob SHA", kind: "concept",
    label: "git blob SHA",
    short: "git 이 파일 내용마다 붙여 둔 지문. 내용이 한 글자라도 바뀌면 값이 달라져 변경을 바로 알 수 있다",
    body: "직접 해시를 계산하지 않고 git 이 이미 가진 값을 그대로 쓴다.",
    links: ["무효화"] },
  { id: "PageRank", kind: "concept",
    label: "PageRank",
    short: "구글이 쓰던 중요도 점수. 많이 참조되는 것을 중요하다고 본다. 여기서는 어느 모듈을 정독할지 고르는 데 쓴다" },
  { id: "hotspot", kind: "concept",
    label: "hotspot",
    short: "자주 바뀌면서 얽힌 곳도 많은 부분. 손대면 파장이 큰 자리다" },
  { id: "모듈", kind: "concept",
    label: "모듈",
    short: "서로 관련된 파일을 묶은 단위. 이 프로젝트에서는 디렉토리 하나가 모듈 하나에 대응한다" },
];

export const data: ReportData = {
  builderVersion: "v1",
  slug: "llm-load-reduction",
  specName: "Track C — LLM 전수조사 부담 감축 조사·구현 계획",
  date: "2026-08-28",
  branch: "feat/report-builder",
  terms,
  decisions: [
    {
      id: "D1",
      title: "계측기를 먼저 만든다 — 모든 “줄였다” 주장은 measure_citation_origin.py 로 잰다 (Task 1)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 95 },
      optionCount: 0,
    },
    {
      id: "D2",
      title: "C-19 · calls[] 는 roslyn-dump.json 에만 넣고 codegraph.json 의 edges[] 로 승격하지 않는다 (Task 2·3·4)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 3,
    },
    {
      id: "D3",
      title: "C-20 · WarmUp 캐시는 파일별 요약 단위, 무효화는 git blob SHA, 판정은 유효 / 낡음 / 판정불가 3값 (Task 5)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 72 },
      optionCount: 0,
    },
    {
      id: "D4",
      title: "C-21 · 모듈을 정독 / 개요 2계층으로 가른다 — PageRank 누적 60% · 순환 참여 · hotspot 상위10 (Task 6)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 62 },
      optionCount: 0,
    },
    {
      id: "D5",
      title: "U3 · 검증 가능한 코드 규약은 이번 계획에서 구현하지 않는다 — 격차를 모르고 규약부터 만들면 거울 함정",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 0,
    },
    {
      id: "D6",
      title: "C++ calls[] 는 보류 — clang-uml 이 호출을 내지 않는다. C# 에서 이득이 확인된 뒤 검토",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 70 },
      optionCount: 0,
    },
  ],
};
