import type { ReportData, Term } from "report-builder/types";

// 용어집 — 정의는 여기 한 곳에만 있다. 본문 인라인 참조도, 관계 그래프도 이 배열에서 나온다.
// 읽는 사람은 배경 지식이 없다고 가정하고 쓴다.
// mental 은 2026-08-29 Mode 1.5 시험(용어 20개 × 5문항, out/term-quiz.md)의 실측이다 — 확실 6 · 애매 3 · 모름 11. 없는 4개는 미측정.
export const terms: Term[] = [
  { id: "C-19", kind: "decision", mental: "모름",
    label: "C-19 호출 관계 수집",
    short: "코드를 읽지 않고도 \u0027A 가 B 를 부른다\u0027 를 알 수 있게, 호출 관계 목록을 미리 뽑아 두기로 한 결정",
    body: "지금은 위키를 쓰는 인공지능이 그 사실을 알려고 소스 코드 본문을 직접 읽는다. 미리 뽑아 두면 읽을 이유가 사라진다. 다만 이 목록을 코드 지도의 간선으로 승격하지는 않는다.",
    links: ["calls[]", "roslyn-dump.json", "codegraph.json"] },
  { id: "C-20", kind: "decision", mental: "모름",
    label: "C-20 요약 캐시",
    short: "파일마다 한 번 읽고 만든 요약을 저장해 두고, 파일이 바뀌었는지는 git 이 이미 가진 지문으로 판별하기로 한 결정",
    body: "같은 파일을 매번 다시 읽지 않게 한다. 판정은 유효 / 낡음 / 판정불가 세 값이다.",
    links: ["WarmUp", "git blob SHA", "무효화"] },
  { id: "C-21", kind: "decision", mental: "모름",
    label: "C-21 두 계층 가르기",
    short: "모든 모듈을 똑같이 정독하지 않고, 중요한 소수만 정독하고 나머지는 개요만 보기로 한 결정",
    body: "무엇이 중요한지는 이미 계산해 둔 세 기준으로 정한다. 무엇을 생략할지는 도구가 정하지 않는다.",
    links: ["PageRank", "hotspot", "모듈"] },
  { id: "calls[]", kind: "artifact", mental: "애매",
    label: "calls[]",
    short: "누가 누구를 부르는지를 모아 둔 목록. 대괄호는 여러 개가 담긴 배열이라는 표시다",
    links: ["roslyn-dump.json"] },
  { id: "roslyn-dump.json", kind: "artifact", mental: "확실",
    label: "roslyn-dump.json",
    short: "C# 코드를 Roslyn 이라는 분석기로 훑어서 나온 원자료 파일. 클래스 이름, 관계, 위치가 들어 있다",
    links: ["codegraph.json"] },
  { id: "codegraph.json", kind: "artifact", mental: "확실",
    label: "codegraph.json",
    short: "원자료를 정리해 만든 코드 지도. 점(클래스)과 선(관계)으로 이루어진다",
    links: ["edges[]"] },
  { id: "edges[]", kind: "artifact", mental: "확실",
    label: "edges[]",
    short: "코드 지도의 선 목록. 무엇이 무엇에 기대고 있는지를 담는다",
    body: "C-19 이 뽑는 호출 관계는 이 목록에 넣지 않는다. 성격이 다른 축이기 때문이다." },
  { id: "WarmUp", kind: "concept", mental: "확실",
    label: "WarmUp",
    short: "미리 데워 둔다는 뜻. 여기서는 파일별 요약을 미리 만들어 두고 다음 번에 다시 쓰는 것을 말한다" },
  { id: "무효화", kind: "concept",
    label: "무효화",
    short: "저장해 둔 값이 더 이상 맞지 않게 됐다고 표시하는 것. 원본이 바뀌면 캐시를 버려야 한다" },
  { id: "git blob SHA", kind: "concept",
    label: "git blob SHA",
    short: "git 이 파일 내용마다 붙여 둔 지문. 내용이 한 글자라도 바뀌면 값이 달라져 변경을 바로 알 수 있다",
    body: "직접 해시를 계산하지 않고 git 이 이미 가진 값을 그대로 쓴다.",
    links: ["무효화"] },
  { id: "PageRank", kind: "concept", mental: "애매",
    label: "PageRank",
    short: "구글이 쓰던 중요도 점수. 많이 참조되는 것을 중요하다고 본다. 여기서는 어느 모듈을 정독할지 고르는 데 쓴다" },
  { id: "hotspot", kind: "concept", mental: "확실",
    label: "hotspot",
    short: "자주 바뀌면서 얽힌 곳도 많은 부분. 손대면 파장이 큰 자리다" },
  { id: "모듈", kind: "concept",
    label: "모듈",
    short: "서로 관련된 파일을 묶은 단위. 이 프로젝트에서는 디렉토리 하나가 모듈 하나에 대응한다" },

  // ── 실측 지표 M — 이 계획이 서 있는 숫자들. 재현 명령이 설계 문서에 있다
  { id: "M1", kind: "concept", mental: "모름",
    label: "M1 정적 계층이 아는 비율",
    short: "위키가 인용한 745곳 중 616곳(82.7%)은 코드를 읽지 않아도 코드 지도만으로 알 수 있는 위치였다는 실측",
    body: "이 숫자가 계획 전체의 논거다. 인공지능이 읽은 8,456줄의 대부분이 사실은 읽을 필요가 없었다는 뜻이다.",
    links: ["M2", "codegraph.json"] },
  { id: "M2", kind: "concept", mental: "모름",
    label: "M2 본문을 읽어야 아는 비율",
    short: "나머지 129곳(17.3%)은 코드 본문을 읽어야 알 수 있었고, 그중 절반(64곳)이 함수 호출식이었다는 실측",
    body: "호출식이 가장 큰 덩어리라서 C-19(호출 관계 수집)가 첫 처방이 됐다.",
    links: ["M1", "C-19", "calls[]"] },
  { id: "M4", kind: "concept", mental: "모름",
    label: "M4 커밋당 변경 파일 수",
    short: "커밋 한 번에 바뀌는 사용자 코드 파일이 114개 중 평균 2개(1.8%)뿐이라는 실측",
    body: "파일이 거의 안 바뀌므로 한 번 만든 요약을 오래 재사용할 수 있다. 이것이 C-20(요약 캐시)의 근거다.",
    links: ["C-20", "WarmUp"] },

  // ── 사용자 확정 사항 U — 착수 전에 사용자가 못 박은 방침
  { id: "U2", kind: "decision", mental: "모름",
    label: "U2 계층화 허용",
    short: "모든 모듈을 똑같이 정독하지 않아도 된다는 사용자 확정. 구조와 시그니처로 싸게 훑고, 중요한 소수만 본문을 정독한다",
    links: ["C-21"] },
  { id: "U3", kind: "decision", mental: "모름",
    label: "U3 검증 가능한 규약만",
    short: "코드 작성 규약은 기계가 어긋남을 잡아낼 수 있는 형식일 때만 받는다는 사용자 확정",
    body: "이번 계획에서는 규약을 만들지 않는다. 격차를 재기 전에 규약부터 만들면 거울 함정이다." },
  { id: "U4", kind: "decision", mental: "모름",
    label: "U4 캐시 단위는 파일별 요약",
    short: "미리 만들어 둘 것은 파일마다 한 개씩의 이해 요약이라는 사용자 확정",
    links: ["WarmUp", "C-20"] },
  { id: "U5", kind: "decision", mental: "모름",
    label: "U5 코드 지도 스키마 확장 허용",
    short: "코드 지도 파일의 형식을 넓혀도 된다는 사용자 확정. M1 을 근거로 호출 관계 목록을 다시 검토하게 했다",
    links: ["codegraph.json", "calls[]", "M1"] },
  { id: "U6", kind: "decision", mental: "모름",
    label: "U6 무효화는 git 기반",
    short: "저장해 둔 요약이 낡았는지를 git 이 가진 지문으로 판별한다는 사용자 확정. 사용자가 착안했다",
    links: ["git blob SHA", "무효화"] },

  // ── 산출물 형식의 세부
  { id: "members[]", kind: "artifact", mental: "애매",
    label: "members[]",
    short: "클래스 안에 들어 있는 변수(멤버 변수) 목록. 원자료 파일에 이미 들어 있다",
    body: "C-19 의 호출 관계 목록도 이것과 같은 자격으로 원자료 파일에 들어간다 — 코드 지도의 간선이 아니라 원자료의 한 칸이다.",
    links: ["roslyn-dump.json", "methods[]"] },
  { id: "methods[]", kind: "artifact", mental: "확실",
    label: "methods[]",
    short: "클래스 안에 들어 있는 함수(메서드) 목록. 원자료 파일에 이미 들어 있다",
    links: ["roslyn-dump.json", "members[]"] },
  { id: "calls.json", kind: "artifact",
    label: "calls.json",
    short: "호출 관계를 별도 파일로 떼어 두는 안. 설계 문서에는 없고, 이 보고서가 비교를 위해 대조군으로 세운 것이다",
    body: "검토된 적 없는 안이다. 옵션표의 판정 열이 그 사실을 표시한다.",
    links: ["calls[]"] },
];

export const data: ReportData = {
  builderVersion: "v1",
  slug: "llm-load-reduction",
  specName: "Track C — LLM 전수조사 부담 감축 조사·구현 계획",
  date: "2026-08-28",
  branch: "feat/report-builder",
  terms,
  linkRoots: ["$CSHARP_REPO/out/codegraph-raw"],
  decisions: [
    {
      id: "D1",
      title: "계측기를 먼저 만든다 — 모든 “줄였다” 주장은 measure_citation_origin.py 로 잰다 (Task 1)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 95 },
      optionCount: 0,
    },
    {
      id: "D2",
      title: "C-19 · calls[] 는 roslyn-dump.json 에만 넣고 codegraph.json 의 edges[] 로 승격하지 않는다 (Task 2·3·4)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 3,
    },
    {
      id: "D3",
      title: "C-20 · WarmUp 캐시는 파일별 요약 단위, 무효화는 git blob SHA, 판정은 유효 / 낡음 / 판정불가 3값 (Task 5)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 72 },
      optionCount: 0,
    },
    {
      id: "D4",
      title: "C-21 · 모듈을 정독 / 개요 2계층으로 가른다 — PageRank 누적 60% · 순환 참여 · hotspot 상위10 (Task 6)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 62 },
      optionCount: 0,
    },
    {
      id: "D5",
      title: "U3 · 검증 가능한 코드 규약은 이번 계획에서 구현하지 않는다 — 격차를 모르고 규약부터 만들면 거울 함정",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 0,
    },
    {
      id: "D6",
      title: "C++ calls[] 는 보류 — clang-uml 이 호출을 내지 않는다. C# 에서 이득이 확인된 뒤 검토",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 70 },
      optionCount: 0,
    },
  ],
};
