import type { ReportData, Term } from "report-builder/types";

// 용어집 — 정의는 여기 한 곳에만 있다. 본문 인라인 참조도, 관계 그래프도 이 배열에서 나온다.
// 읽는 사람은 배경 지식이 없다고 가정한다 (객체지향을 갓 배운 1학년 눈높이).
// mental 은 비워 둔다 — 이 Plan 에 대한 Mode 1.5 용어 이해도 측정을 아직 돌리지 않았다.
export const terms: Term[] = [
  // ── 도구
  { id: "griffe", kind: "tool",
    label: "griffe",
    short: "파이썬 코드를 실행하지 않고 읽기만 해서 클래스·함수·타입 목록을 뽑아 주는 기성 라이브러리",
    body: "이번에 새로 쓰기 시작한 도구다. 우리가 직접 파서를 만드는 대신 이것이 낸 JSON 을 받아서 우리 형식으로 옮긴다. 설치된 버전은 2.2.0 이다.",
    links: ["clang-uml", "roslyn-dump", "식 트리", "codegraph.json"] },
  { id: "clang-uml", kind: "tool",
    label: "clang-uml",
    short: "C++ 코드에서 클래스와 관계를 뽑아 주는 기성 도구. 이 파이프라인의 첫 번째 언어 갈래다",
    links: ["codegraph.json"] },
  { id: "roslyn-dump", kind: "tool",
    label: "roslyn-dump",
    short: "C# 코드에서 클래스와 관계를 뽑는, 이 저장소가 직접 만든 도구. 두 번째 언어 갈래다",
    links: ["codegraph.json"] },

  // ── 산출물
  { id: "codegraph.json", kind: "artifact",
    label: "codegraph.json",
    short: "언어가 무엇이든 똑같은 모양으로 정리된 코드 지도. 점(클래스)과 선(관계)으로 이루어진다",
    body: "언어별 도구가 내는 원자료는 제각각이지만, 전부 이 하나의 형식으로 옮겨진다. 그래야 그 뒤 단계가 언어를 몰라도 된다.",
    links: ["_assemble", "kind"] },
  { id: "식 트리", kind: "artifact",
    label: "식 트리 (expression tree)",
    short: "타입 표기를 글자 그대로가 아니라 조각으로 분해해 담아 둔 자료. 껍데기와 알맹이가 이미 나뉘어 있다",
    body: "예를 들어 list[Foo] 를 'list 라는 껍데기 + Foo 라는 알맹이' 로 나눠서 준다. 글자 \"list[Foo]\" 를 받아 직접 잘라 읽을 필요가 없다는 뜻이고, 이번 검토의 핵심 발견이다.",
    links: ["griffe", "R5"] },

  // ── 개념 (접기 규칙)
  { id: "R5", kind: "concept",
    label: "R5 — 컨테이너 투과",
    short: "list[Foo] 처럼 무언가를 담는 그릇을 만나면, 그릇 말고 안에 든 Foo 를 관계 상대로 삼는 규칙",
    body: "그릇 자체는 관심사가 아니다. 이 규칙이 없으면 목록·사전에 담아 둔 관계가 통째로 사라진다.",
    links: ["식 트리", "R7"] },
  { id: "R7", kind: "concept",
    label: "R7 — 원시 타입 제외",
    short: "글자·정수·참거짓 같은 기본 타입은 코드 지도의 점으로 만들지 않는다는 규칙",
    links: ["R5"] },
  { id: "kind", kind: "concept",
    label: "kind (관계 종류)",
    short: "선의 종류를 나타내는 8개짜리 고정 목록. 상속·의존·연관 등이 들어 있다",
    body: "8종은 고정이라 새로 만들 수 없다. 파이썬 갈래는 그중 셋(상속·연관·의존)만 쓴다.",
    links: ["소유 kind", "codegraph.json"] },
  { id: "소유 kind", kind: "concept",
    label: "소유 kind",
    short: "'A 가 B 를 통째로 데리고 있다' 를 뜻하는 관계 종류(composition·aggregation)",
    body: "C++ 은 값으로 담았는지 주소로 가리켰는지 구분되므로 이 관계를 알 수 있다. C# 과 파이썬은 그 구분이 언어에 없어서 쓰지 않는다.",
    links: ["kind"] },
  { id: "_assemble", kind: "concept",
    label: "_assemble()",
    short: "언어별 갈래들이 마지막에 다 같이 거쳐 가는 공통 마무리 함수. 여기서 최종 파일 모양이 만들어진다",
    body: "새 언어를 더할 때 이 함수를 다시 만들면 안 된다 — 그대로 불러 쓴다. 그래야 세 언어가 같은 결과 형식을 보장한다.",
    links: ["codegraph.json"] },
  { id: "자기호스팅", kind: "concept",
    label: "자기호스팅",
    short: "만든 도구를 그 도구가 사는 저장소 자신에게 써 보는 것. 남의 저장소 없이도 시험할 수 있다",
    body: "이번엔 잘 통하지 않는다. 이 저장소의 파이썬 코드에 클래스가 거의 없어서 검사할 것이 남지 않기 때문이다.",
    links: ["골든 테스트"] },
  { id: "골든 테스트", kind: "concept",
    label: "골든 테스트",
    short: "실제 저장소를 돌려 나온 결과를 기준값으로 박아 두고, 나중에 달라지면 알아채게 하는 시험",
    body: "지어낸 자료만으로 시험하면 실제 도구의 출력이 바뀌었을 때 아무도 모른다.",
    links: ["자기호스팅"] },
  { id: "거울 함정", kind: "concept",
    label: "거울 함정",
    short: "과잉 설계를 잡으려고 만든 도구를 정작 과잉 설계하는 실수",
    body: "쓰는 곳이 하나뿐인데 플러그인 구조나 추상 인터페이스를 만드는 것이 그 예다. 이 저장소가 명시적으로 금지한다.",
    links: ["_assemble"] },

  { id: "R11", kind: "decision",
    label: "R11 — 형식 확장",
    short: "코드 지도 파일에 위치·링크 정보를 더 담자는, 아직 승인되지 않은 열린 결정",
    body: "이번 작업의 범위 밖이다. 별도로 판단할 것이라 여기서 건드리지 않는다.",
    links: ["codegraph.json"] },

  // ── 결정
  { id: "Option B", kind: "decision",
    label: "Option B",
    short: "정적 수집기를 파이썬만 먼저 시험해 보기로 한 선택. 자바스크립트 쪽은 범위 밖으로 뒀다",
    links: ["griffe"] },
];

export const data: ReportData = {
  builderVersion: "v1",
  slug: "griffe-python-collector",
  specName: "griffe 기반 Python 정적 수집기 — 설계 검토",
  date: "2026-08-30",
  branch: "main",
  terms,
  decisions: [
    {
      id: "D0",
      title: "griffe 를 Python 정적 수집기로 채택한다 (Option B) — 자작 파서를 만들지 않는다",
      variant: "accepted",
      statusText: "[승인됨]",
      conf: { tier: "green", anchor: 92 },
      optionCount: 2,
    },
    {
      id: "D1",
      title: "R5(컨테이너 투과)를 이번 범위에 포함한다 — 인계 문서의 제외 지시를 뒤집는다",
      variant: "superseded",
      statusText: "[번복됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 2,
    },
    {
      id: "D2",
      title: "골든 테스트 대상은 합성 픽스처 + 빈약한 자기호스팅 — 외부 저장소에 기대지 않는다",
      variant: "accepted",
      statusText: "[승인됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 3,
    },
    {
      id: "D3",
      title: "kind 사상은 association-only — 소유 kind 를 만들지 않는다 (C# 과 같은 이유)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 0,
    },
    {
      id: "D4",
      title: "노드 입도는 클래스로 둔다 — 모듈 수준 함수는 이번 범위 밖 (정보 손실을 감수한다)",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 70 },
      optionCount: 2,
    },
    {
      id: "D5",
      title: "모듈 경계는 기존 module_of() 를 재사용한다 — 중복 함수를 만들지 않는다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 78 },
      optionCount: 2,
    },
  ],
};
