import type { ReportData, Term } from "report-builder/types";

// 용어집 — 정의는 여기 한 곳에만 있다. 본문 인라인 참조도, 관계 그래프도 이 배열에서 나온다.
// 읽는 사람은 배경 지식이 없다고 가정하고 쓴다 (객체지향을 갓 배운 대학 1학년).
export const terms: Term[] = [
  // ── 산출물
  { id: "terms-db.json", kind: "artifact", label: "terms-db.json",
    short: "코드베이스의 낱말 사전. 낱말마다 뜻 · 위치 · 관계가 한 레코드에 들어 있다. 이 계획에서 원본이 되는 파일",
    body: "Mode 1.5 가 시험 문제를 낼 때 정답지로 쓰고, codegraph.json 은 여기서 뽑아 만든다.",
    links: ["codegraph.json", "terms-reading.json", "means", "uses[]", "where", "투영"] },
  { id: "codegraph.json", kind: "artifact", label: "codegraph.json",
    short: "코드 지도. 점(클래스 · 함수)과 선(관계)만 담는다. 이 계획부터는 terms-db.json 에서 뽑아 만든 부분집합이다",
    links: ["terms-db.json", "nodes[]", "edges[]", "부분집합", "verify_citations.py"] },
  { id: "terms-reading.json", kind: "artifact", label: "terms-reading.json",
    short: "인공지능이 코드를 한 번 읽고 쓴 낱말 사전 원고. 사람이 쓴 문서처럼 git 에 넣는다",
    body: "terms-db.json 과 codegraph.json 은 이 파일에서 명령 한 줄로 다시 만들 수 있으므로 git 에 넣지 않는다.",
    links: ["terms-db.json", "전수조사", "mode-1-codebase-wiki"] },
  { id: "nodes[]", kind: "artifact", label: "nodes[]",
    short: "코드 지도의 점 목록. 클래스 · 함수 하나가 점 하나다. 대괄호는 여러 개가 담긴 배열이라는 표시",
    links: ["codegraph.json"] },
  { id: "edges[]", kind: "artifact", label: "edges[]",
    short: "코드 지도의 선 목록. 누가 누구에게 기대는지를 담는다. 방향 · 종류 · 위치가 있다",
    links: ["codegraph.json", "uses[]"] },
  { id: "calls[]", kind: "artifact", label: "calls[]",
    short: "누가 누구를 부르는지 모아 둔 목록. 앞선 계획(llm-load-reduction)이 만들기로 한 것이라 시험 문제의 필수 낱말이다",
    links: ["Mode 1.5"] },

  // ── 레코드의 칸
  { id: "means", kind: "concept", label: "means",
    short: "레코드의 '무엇인가' 칸. 지금은 기계가 만든 정형문이고, 이 계획부터는 인공지능이 코드를 읽고 쓴 한 문장",
    links: ["does", "terms-db.json", "C1"] },
  { id: "does", kind: "concept", label: "does",
    short: "레코드의 '무엇을 하는가' 칸. 함수나 클래스의 동작을 한두 문장으로. 없어도 된다",
    links: ["means"] },
  { id: "where", kind: "concept", label: "where",
    short: "레코드의 위치 칸. '파일:줄' 꼴. 인공지능이 쓴 레코드는 이 칸이 없으면 실패다",
    body: "코드에 그 낱말이 없으면 낱말 사전에 싣지 않는다 — 인용 없는 뜻은 없다.",
    links: ["L1", "L2", "L3", "terms-db.json"] },
  { id: "uses[]", kind: "concept", label: "uses[]",
    short: "레코드의 관계 칸. 이 낱말이 무엇을 부르거나 · 가져오거나 · 상속하는지를 방향 있게 적는다. 코드 지도의 선이 여기서 나온다",
    links: ["edges[]", "구조 필드"] },
  { id: "source", kind: "concept", label: "source",
    short: "레코드의 출처 칸. codegraph(정적 도구) · reading(인공지능) · codegraph+reading(합친 것) 셋 중 하나",
    links: ["정적 수집기", "전수조사"] },
  { id: "구조 필드", kind: "concept", label: "구조 필드",
    short: "id · kind · module · where 네 칸. 정적 도구가 있으면 인공지능이 이 네 칸을 덮어쓰지 못한다 (D3)",
    links: ["정적 수집기", "결정론"] },

  // ── 개념
  { id: "투영", kind: "concept", label: "투영 (projection)",
    short: "큰 표에서 필요한 열만 뽑아 작은 표를 만드는 것. codegraph.json 은 terms-db.json 을 그렇게 뽑은 것이다",
    links: ["부분집합", "codegraph.json"] },
  { id: "부분집합", kind: "concept", label: "부분집합",
    short: "한 집합의 원소가 전부 다른 집합에도 들어 있을 때. 코드 지도의 점 · 선 · 모듈이 전부 낱말 사전에 있어야 한다는 뜻",
    body: "이것이 기계 검사 항목이다 — 정적 도구의 codegraph.json 노드 231개가 투영에 전부 있는지 센다.",
    links: ["투영", "골든 테스트"] },
  { id: "결정론", kind: "concept", label: "결정론 (determinism)",
    short: "같은 입력이면 항상 같은 출력. 인공지능은 그렇지 않으므로, 인공지능이 쓴 것은 인용으로 붙들고 나머지는 기계가 한다",
    links: ["구조 필드", "L1", "전수조사"] },
  { id: "전수조사", kind: "concept", label: "전수조사",
    short: "코드베이스의 파일을 빠짐없이 읽고 낱말마다 뜻 · 동작 · 관계 · 위치를 적는 일. 인공지능이 한 번만 한다",
    links: ["terms-reading.json", "mode-1-codebase-wiki", "키 규칙"] },
  { id: "키 규칙", kind: "concept", label: "키 규칙",
    short: "낱말 사전에서 낱말의 이름을 정하는 법. 파일은 파일명, 함수는 맨 이름, 이름이 겹치면 '파일.이름' (D5)",
    links: ["전수조사"] },
  { id: "L1", kind: "concept", label: "L1 파일",
    short: "인용 검사 1단계 — 그 파일이 있는가. 없으면 실패",
    links: ["L2", "where"] },
  { id: "L2", kind: "concept", label: "L2 줄",
    short: "인용 검사 2단계 — 그 파일에 그 줄이 있는가. 없으면 실패",
    links: ["L3"] },
  { id: "L3", kind: "concept", label: "L3 이름",
    short: "인용 검사 3단계 — 그 줄 앞뒤에 그 낱말이 있는가. 없으면 '근거 없음'. 실패가 아니라 경고다",
    links: ["근거 없음"] },
  { id: "근거 없음", kind: "concept", label: "근거 없음",
    short: "파일과 줄은 있는데 그 자리에 그 낱말이 안 보이는 상태. 실패로 세면 정상 인용까지 죽고, 통과로 세면 검사가 무의미해서 따로 센다",
    links: ["L3", "verify_citations.py"] },
  { id: "골든 테스트", kind: "concept", label: "골든 테스트",
    short: "지어낸 데이터가 아니라 실제 저장소의 산출물로 돌리는 테스트. 이 계획은 C# · C++ 저장소 둘의 codegraph.json 을 쓴다",
    links: ["StickRush", "부분집합"] },
  { id: "C1", kind: "concept", label: "C1 우려",
    short: "시험 문제의 오답 보기가 정형문 때문에 그럴듯하지 않을 것이라는 미해소 우려. 진짜 뜻이 담긴 사전으로만 시험할 수 있다",
    links: ["means", "Mode 1.5"] },
  { id: "StickRush", kind: "concept", label: "StickRushGame 저장소",
    short: "이 도구를 이미 한 번 돌려 본 C# 게임 저장소. codegraph.json 이 있어 골든 테스트 재료가 된다",
    links: ["골든 테스트"] },

  // ── 도구
  { id: "terms_db.py", kind: "tool", label: "terms_db.py",
    short: "낱말 사전을 만드는 파이썬 스크립트. 이 계획에서 합치기 · 인용 검사 · 투영 세 기능이 더해진다",
    links: ["terms-db.json", "codegraph.json", "normalize.py"] },
  { id: "normalize.py", kind: "tool", label: "normalize.py",
    short: "정적 수집기의 원자료를 codegraph.json 으로 정리하는 파이썬 스크립트. 이 계획은 이것을 읽기만 한다",
    links: ["정적 수집기", "codegraph.json"] },
  { id: "verify_citations.py", kind: "tool", label: "verify_citations.py",
    short: "문서의 '파일:줄' 인용이 진짜인지 코드 지도와 대조하는 파이썬 스크립트. 이 계획의 인용 검사는 그 규칙을 그대로 빌린다",
    links: ["L1", "L2", "L3", "codegraph.json"] },
  { id: "정적 수집기", kind: "tool", label: "정적 수집기",
    short: "코드를 실행하지 않고 읽어서 클래스와 관계를 뽑는 도구. C# 은 roslyn, C++ 은 clang-uml. 파이썬 · 자바스크립트용은 없다",
    links: ["normalize.py", "구조 필드"] },
  { id: "mode-1-codebase-wiki", kind: "tool", label: "mode-1-codebase-wiki",
    short: "Mode 1(코드베이스 위키)을 맡는 서브에이전트. 전수조사를 이것이 한다 (D6)",
    links: ["전수조사", "Mode 1.5"] },
  { id: "Mode 1.5", kind: "tool", label: "Mode 1.5",
    short: "읽는 사람이 낱말을 아는지 객관식으로 재는 단계. 정답지가 terms-db.json 이라 이 계획의 직접 소비자다",
    links: ["terms-db.json", "C1"] },
];

export const data: ReportData = {
  builderVersion: "v1",
  slug: "mode-1-terms-db-first",
  specName: "Mode 1 terms-db 우선 파이프라인 Implementation Plan",
  date: "2026-08-29",
  branch: "feat/report-builder",
  terms,
  decisions: [
    {
      id: "D1",
      title: "terms-db.json 이 원본이고 codegraph.json 은 그 투영이다 — 인공지능 전수조사는 1회 (Task 1 · 2 · 5)",
      variant: "proposed",
      statusText: "[제안됨] · 사용자 확정",
      conf: { tier: "green", anchor: 95 },
      optionCount: 2,
    },
    {
      id: "D2",
      title: "인공지능이 쓴 레코드는 where 가 필수이고 L1 · L2 · L3 3값으로 기계 검사한다 — 인용 없는 뜻은 싣지 않는다 (Task 3)",
      variant: "proposed",
      statusText: "[제안됨] · 사용자 확정",
      conf: { tier: "green", anchor: 92 },
      optionCount: 0,
    },
    {
      id: "D3",
      title: "정적 수집기가 있으면 구조 필드는 codegraph 가 이긴다 — 인공지능은 means · does · 새 uses 만 보탠다 (Task 4)",
      variant: "proposed",
      statusText: "[제안됨] · 사용자 확정 (1안)",
      conf: { tier: "amber", anchor: 75 },
      optionCount: 3,
    },
    {
      id: "D4",
      title: "읽기 원본 terms-reading.json 은 docs/codegraph/ 에 추적하고, 파생물은 out/ 에 두고 재생성한다 (Task 7)",
      variant: "proposed",
      statusText: "[제안됨] · 사용자 확정 (1안)",
      conf: { tier: "amber", anchor: 70 },
      optionCount: 3,
    },
    {
      id: "D5",
      title: "키 규칙 — 파일은 파일명, 함수는 맨 이름, 겹치면 전원 '파일줄기.이름', module 은 디렉토리 (Task 6)",
      variant: "proposed",
      statusText: "[제안됨] · 사용자 확정 (1안)",
      conf: { tier: "amber", anchor: 70 },
      optionCount: 2,
    },
    {
      id: "D6",
      title: "전수조사는 mode-1-codebase-wiki 가 하고 오케스트레이터는 검토 · 커밋만 한다 (Task 6 · 7)",
      variant: "proposed",
      statusText: "[제안됨] · 사용자 확정",
      conf: { tier: "green", anchor: 95 },
      optionCount: 0,
    },
    {
      id: "D7",
      title: "C# 저장소에 읽기 단계를 적용해 C1 을 시험하는 것은 이 계획 밖 — 기록만",
      variant: "proposed",
      statusText: "[제안됨] · 기록만",
      conf: { tier: "red", anchor: 55 },
      optionCount: 0,
    },
  ],
};
