import type { ReportData } from "report-builder/types";

export const data: ReportData = {
  builderVersion: "v1",
  slug: "symbol-resolution-survey",
  specName: "전수조사 심볼 해석(Symbol Resolution) 개선 Implementation Plan",
  date: "2026-08-30",
  branch: "main",

  decisions: [
    {
      id: "D1",
      title: "두 갈래로 고친다 — 원인 제거와 사후 해석을 함께 넣는다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: "실측" },
      optionCount: 0,
    },
    {
      id: "D2",
      title: "계획 파일의 의존 목록을 내부 번호가 아니라 사람이 읽는 이름으로 낸다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 92 },
      optionCount: 0,
    },
    {
      id: "D3",
      title: "해석 사다리는 되돌리기를 먼저 보고 합성을 나중에 본다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 75 },
      optionCount: 3,
    },
    {
      id: "D4",
      title: "짧은 이름이 둘 이상이면 해석을 포기한다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 78 },
      optionCount: 3,
    },
    {
      id: "D5",
      title: "저장소 밖 라이브러리 접두사 목록은 사람이 손으로만 늘린다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "red", anchor: 55 },
      optionCount: 0,
    },
    {
      id: "D6",
      title: "끝내 못 푼 참조는 「실패」가 아니라 「근거 없음」이다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "green", anchor: 90 },
      optionCount: 3,
    },
    {
      id: "D7",
      title: "합성 데이터가 아니라 실제 저장소 레코드로 사다리를 대조한다",
      variant: "proposed",
      statusText: "[제안됨]",
      conf: { tier: "amber", anchor: 65 },
      optionCount: 0,
    },
  ],

  // 용어집 — 뜻과 선정은 이 보고서 저자의 판단이고, mental 은 Mode 1.5 실측이다.
  // 출처: out/mode1_5/symbol-resolution-survey/terms.json (20개 용어 · 60문항).
  // mental 이 없는 용어는 그 시험의 출제 범위 밖이라 측정되지 않았다 — "미측정" 으로 뜬다.
  terms: [
    {
      id: "전수조사",
      label: "전수조사",
      short: "저장소의 모든 심볼을 하나도 빠뜨리지 않고 읽어 사전으로 적어 두는 단계다.",
      body: "코드 안의 클래스·함수 하나하나를 대상으로 「이것은 무엇을 하는가」 를 적은 레코드를 만든다. 사람이 읽는 위키를 쓰기 전에, 기계가 아는 사실을 먼저 굳혀 두려는 것이다. 이 단계의 산출물이 terms-reading.json 이다.",
      kind: "concept",
      links: ["terms-reading.json", "codegraph.json", "Bottom-Up 층"],
    },
    {
      id: "codegraph.json",
      label: "codegraph.json",
      short: "정적 도구가 코드에서 뽑아낸 심볼 목록과 그 사이의 화살표를 담은 파일, 곧 코드 지도다.",
      body: "노드(nodes)와 간선(edges) 두 배열로 되어 있다. 노드 하나가 클래스 또는 함수 하나이고, 간선 하나가 「A 가 B 를 쓴다」 는 화살표다. 노드에는 사람이 읽는 이름(name)과 별개로 기계가 붙인 짧은 번호(id)가 함께 들어 있다.",
      kind: "artifact",
      mental: "확실",
      links: ["내부 번호", "survey-plan.json", "전수조사"],
    },
    {
      id: "내부 번호",
      label: "내부 번호(C10 꼴)",
      short: "정적 도구가 심볼마다 붙인 기계용 식별자다. 사람이 보아도 무엇인지 알 수 없다.",
      body: "코드 지도 안에서만 뜻이 있는 이름표다. C10 이라는 글자만 보고는 그것이 AlignmentOptions 인지 무엇인지 알 방법이 없다. 이 계획의 결함 두 건이 모두 이 번호가 바깥으로 새어 나간 데서 나왔다.",
      kind: "concept",
      links: ["codegraph.json", "depends_on", "uses.to"],
    },
    {
      id: "survey-plan.json",
      label: "survey-plan.json",
      short: "코드 지도를 층과 배치로 나눠 「어느 순서로 무엇을 읽을지」 를 적어 둔 작업 계획서다.",
      body: "의존하는 것이 없는 심볼부터 0층에 놓고, 그것에 기대는 심볼을 1층에 놓는 식으로 층을 쌓는다. 같은 층 안은 여러 배치로 쪼개 동시에 읽는다. 배치마다 자기 심볼과 그 심볼이 기대는 대상 목록(depends_on)이 함께 적힌다.",
      kind: "artifact",
      mental: "확실",
      links: ["depends_on", "Bottom-Up 층", "codegraph.json"],
    },
    {
      id: "depends_on",
      label: "depends_on",
      short: "배치 안의 심볼 하나가 기대고 있는 다른 심볼들의 목록이다.",
      body: "「이 함수를 이해하려면 저것들을 먼저 알아야 한다」 는 뜻이다. 지금은 이 목록에 내부 번호가 들어가 있다. 이름이 들어가야 아래층 발췌가 붙는다.",
      kind: "artifact",
      links: ["survey-plan.json", "dep_excerpt", "내부 번호"],
    },
    {
      id: "dep_excerpt",
      label: "dep_excerpt",
      short: "배치가 기대는 아래층 심볼들의 뜻을 짧게 오려 붙여 주는 함수다.",
      body: "「너보다 아래층은 이미 끝났으니 다시 조사하지 마라」 는 지시를 프롬프트에 실어 주는 장치다. depends_on 에 적힌 이름으로 terms-reading.json 을 뒤져 이미 완성된 레코드만 골라 낸다. 이름 대신 번호가 오면 뒤져도 아무것도 나오지 않는다.",
      kind: "tool",
      links: ["depends_on", "terms-reading.json", "Bottom-Up 층"],
    },
    {
      id: "terms-reading.json",
      label: "terms-reading.json",
      short: "전수조사가 읽어 낸 심볼 레코드 사전이다. 열쇠가 사람이 읽는 이름이다.",
      body: "심볼 이름 하나에 그 뜻(means)·있는 자리(where)·쓰는 것들(uses)이 딸린 사전이다. 열쇠가 이름이라는 점이 중요하다 — 번호로 찾으면 영원히 못 찾는다.",
      kind: "artifact",
      mental: "모름",
      links: ["uses.to", "dep_excerpt", "전수조사"],
    },
    {
      id: "uses.to",
      label: "uses.to",
      short: "레코드가 「나는 이것을 쓴다」 며 가리키는 상대 심볼의 이름이다.",
      body: "레코드마다 uses 배열이 있고 그 안의 to 칸이 가리키는 대상이다. 가리킨 이름이 사전에 없으면 지금은 검사가 그 자리에서 파이프라인을 멈춘다. 이 계획이 손대는 곳이 바로 여기다.",
      kind: "artifact",
      mental: "모름",
      links: ["terms-reading.json", "resolve_uses", "근거 없음"],
    },
    {
      id: "해석 사다리",
      label: "해석 사다리",
      short: "사전에 없는 참조를 정해진 순서로 처리하는 절차다. 정확한 조상 → 짧은 이름 → 저장소 밖·파일 합성 → 근거 없음 순으로 내려간다.",
      body: "사다리라 부르는 것은 위 칸에서 풀리면 아래 칸을 보지 않기 때문이다. 첫 칸이 되돌리기(rollup), 마지막 칸이 격하다. 이 계획의 D3·D4·D6 이 전부 이 사다리의 어느 칸을 어떻게 놓을지에 대한 결정이다.",
      kind: "concept",
      mental: "모름",
      links: ["resolve_target", "rollup", "synthesize_record", "근거 없음"],
    },
    {
      id: "resolve_target",
      label: "resolve_target",
      short: "사전에 없는 이름을 사전이 아는 이름으로 되돌려 주는 순수 함수다. 못 하면 아무것도 내지 않는다.",
      body: "링커가 목적 파일 여럿에서 같은 심볼을 맞춰 붙이는 일과 같은 문제다. 하나의 실체를 여러 표기가 가리킨다. 정확한 조상을 먼저 보고, 그것이 없으면 짧은 이름이 딱 하나로 좁혀질 때만 쓴다.",
      kind: "tool",
      links: ["rollup", "resolve_uses", "uses.to"],
    },
    {
      id: "rollup",
      label: "rollup(되돌리기)",
      short: "긴 이름을 그 이름을 품은 더 짧은 조상 이름으로 바꿔 다는 것이다.",
      body: "A::B::C 가 사전에 없고 A::B 가 있으면 A::B 로 바꿔 단다. 「AddHandler 라는 멤버 함수는 없지만 그것이 속한 MessageRouter 는 안다」 는 식으로 한 칸 물러서는 것이다. 가리키는 정밀도를 조금 잃는 대신 화살표가 끊기지 않는다.",
      kind: "concept",
      mental: "모름",
      links: ["resolve_target", "synthesize_record"],
    },
    {
      id: "synthesize_record",
      label: "synthesize_record",
      short: "되돌릴 수는 없지만 분류는 되는 이름에 대해 사전 레코드를 새로 만들어 주는 순수 함수다.",
      body: "되돌리기와 달리 원래 이름을 그대로 두고, 그 이름짜리 레코드를 사전에 새로 얹는다. 정밀도를 잃지 않는 대신 분류 규칙을 사람이 유지해야 한다. 아는 접두사로 시작하거나 실제로 그 파일이 저장소에 있을 때만 만든다.",
      kind: "tool",
      links: ["EXTERNAL_PREFIXES", "external", "rollup"],
    },
    {
      id: "EXTERNAL_PREFIXES",
      label: "EXTERNAL_PREFIXES",
      short: "저장소 밖 라이브러리의 이름 앞머리를 모아 둔 고정 목록이다.",
      body: "cv:: std:: Ui:: Qt:: boost:: 다섯이다. 이 중 하나로 시작하는 이름은 우리 코드가 아니라 남의 라이브러리라고 본다. 목록이 늘어난다는 것은 정적 수집기가 우리 심볼을 놓쳤다는 신호일 수도 있어, 자동으로 늘리지 않는다.",
      kind: "artifact",
      links: ["external", "synthesize_record"],
    },
    {
      id: "external",
      label: "external(저장소 밖)",
      short: "우리 저장소에 소스가 없는 남의 라이브러리 심볼을 뜻하는 레코드 종류다.",
      body: "레코드 스키마는 처음부터 이 종류를 받아들이게 되어 있었다. 없던 것은 그 자리를 채우는 절차였다. 소스가 없으므로 있는 자리(where)를 비워 둔다.",
      kind: "concept",
      links: ["EXTERNAL_PREFIXES", "synthesize_record"],
    },
    {
      id: "resolve_uses",
      label: "resolve_uses",
      short: "사전 전체를 훑으며 되돌리기와 합성을 차례로 걸고, 끝내 못 푼 것은 목록으로 돌려주는 배선 함수다.",
      body: "받은 사전을 바꾸지 않고 복사본을 고쳐서 돌려준다. 되돌린 것은 가리키는 이름 자체가 바뀌고, 합성한 것은 이름이 그대로 남고 사전에 열쇠가 하나 는다. 못 푼 것은 조용히 지우지 않고 (용어, 대상) 짝의 목록으로 돌려준다.",
      kind: "tool",
      links: ["resolve_target", "synthesize_record", "근거 없음", "uses.to"],
    },
    {
      id: "근거 없음",
      label: "근거 없음",
      short: "검사 결과 세 값 중 하나다. 문제로 적어 남기되 파이프라인을 멈추지는 않는다.",
      body: "「실패」 는 파이프라인을 멈춰 세우고, 「근거 없음」 은 기록만 남기고 통과시킨다. 세션이 실제로 읽은 심볼인데 정적 수집기가 노드로 뽑지 않은 경우(익명 이름공간의 상수 같은 것)가 섞여 있어서, 그것만으로 멈추는 것은 지나치다는 판단이다.",
      kind: "decision",
      mental: "모름",
      links: ["uses.to", "resolve_uses"],
    },
    {
      id: "K5",
      label: "K5(비노드 층 제약)",
      short: "그래프 노드가 아닌 용어는 심볼을 다 읽은 뒤 맨 마지막 층에서 한꺼번에 처리한다는 규약이다.",
      body: "파일 · 모듈 · 산출물 이름처럼 코드 지도에 노드로 잡히지 않는 용어들이 여기 모인다. 이 계획은 K5 를 건드리지 않는다 — 그 층을 쪼개 병렬로 돌리려면 규약 자체를 바꿔야 하고, 그것은 별도 결정이기 때문이다.",
      kind: "concept",
      mental: "모름",
      links: ["Bottom-Up 층", "survey-plan.json"],
    },
    {
      id: "Bottom-Up 층",
      label: "Bottom-Up 층",
      short: "기대는 것이 없는 심볼부터 읽고 위층으로 올라가는 조사 순서 규약이다.",
      body: "아래층을 먼저 확정해 두면 위층을 읽는 세션이 아래층을 다시 조사하지 않아도 된다. 그 「다시 조사하지 마라」 를 실제로 실어 나르는 장치가 dep_excerpt 다. 발췌가 비어 있으면 층을 나눈 의미가 사라진다.",
      kind: "concept",
      links: ["dep_excerpt", "survey-plan.json", "전수조사"],
    },
    {
      id: "골든 시험",
      label: "골든 시험",
      short: "지어낸 데이터가 아니라 실제 저장소의 산출물을 재료로 돌리는 시험이다.",
      body: "환경 변수로 가리킨 바깥 저장소가 있을 때만 돌고, 없으면 건너뛴다(실패가 아니다). 이 계획의 결함 두 건이 모두 지어낸 데이터를 통과했기 때문에 필요해진 장치다.",
      kind: "concept",
      links: ["전수조사", "terms-reading.json"],
    },
  ],
};
